### PR TITLE
Small arithmetic simplification

### PR DESCRIPTION
**Pull request by canni**
IMO this reads nicer, and it's easier to understand :)

### CODE REVIEW

**Comment by eapache** [comment]
I don't disagree stylistically, but these changes do add about 5% to the benchmark times on my machine, which isn't ideal.

**Comment by canni** [comment]
That is strange, but looks like it's second commit causes slowdown, first actually gives ~5% speedup
Try again with only first of two commits

**Comment by eapache** [comment]
Yup, first commit on its own seems to give a (marginal) speed-up. I think that makes sense; `len(foo)` looks like a function call but I believe it reduces to just a variable access, so storing it in a variable explicitly just makes more work for the compiler.

Push the branch back to just the first commit and I'll merge this.

**Comment by canni** [comment]
@eapache done

**Pull request merged**
